<?php
$privacidad_content = '<h2>1. ¿Quiénes somos?</h2><p>Vitrinexo es una plataforma de directorio B2B para empresas de servicios profesionales. Puedes contactarnos en <a href="mailto:hola@vitrinexo.com">hola@vitrinexo.com</a>.</p><h2>2. ¿Qué datos recopilamos?</h2><p>Al registrarte en Vitrinexo recopilamos los siguientes datos personales:</p><ul><li>Nombre y apellido</li><li>Dirección de correo electrónico</li><li>Empresa y cargo</li><li>Perfil de LinkedIn</li><li>País de residencia</li><li>Número de teléfono celular</li></ul><p>Adicionalmente, recopilamos datos de uso de la plataforma para mejorar la experiencia (páginas visitadas, conexiones realizadas, actividad general).</p><h2>3. ¿Para qué usamos tus datos?</h2><p>Usamos tu información para:</p><ul><li>Crear y gestionar tu perfil en la plataforma</li><li>Facilitar conexiones entre miembros</li><li>Enviarte comunicaciones relacionadas con tu cuenta y la plataforma</li><li>Mejorar nuestros servicios</li><li>Cumplir con obligaciones legales</li></ul><h2>4. ¿Con quién compartimos tus datos?</h2><p>Tu perfil (nombre, empresa, cargo, industria) es visible para otros miembros verificados de Vitrinexo. No vendemos ni cedemos tus datos personales a terceros con fines comerciales.</p><h2>5. ¿Cuánto tiempo guardamos tus datos?</h2><p>Mantenemos tus datos mientras tu cuenta esté activa. Puedes solicitar la eliminación de tus datos en cualquier momento escribiendo a hola@vitrinexo.com.</p><h2>6. Tus derechos</h2><p>Tienes derecho a acceder, corregir, eliminar y portar tus datos, y a oponerte a su uso con fines de marketing. Escríbenos a <a href="mailto:hola@vitrinexo.com">hola@vitrinexo.com</a>.</p><h2>7. Cookies</h2><p>Vitrinexo utiliza cookies esenciales para el funcionamiento de la plataforma. No utilizamos cookies de seguimiento publicitario.</p><h2>8. Modificaciones</h2><p>Podemos actualizar esta política periódicamente. Te notificaremos por email ante cambios significativos.</p>';

$terminos_content = '<h2>1. Aceptación</h2><p>Al registrarte y utilizar Vitrinexo aceptas estos Términos y Condiciones.</p><h2>2. La plataforma</h2><p>Vitrinexo es un directorio B2B de empresas de servicios profesionales que facilita visibilidad y conexiones entre miembros.</p><h2>3. Elegibilidad</h2><p>Para registrarte debes ser mayor de 18 años, representar a una empresa o ejercer actividad profesional, y proporcionar información verdadera.</p><h2>4. Uso aceptable</h2><p>Queda prohibido publicar contenido falso o engañoso, hacer spam, infringir derechos de terceros o intentar acceder sin autorización a sistemas de la plataforma.</p><h2>5. Membresía y pagos</h2><p>Los primeros 100 Miembros Pioneros acceden a 3 meses gratuitos desde el lanzamiento. Transcurrido ese período el acceso podrá requerir suscripción. Los precios serán comunicados con anticipación.</p><h2>6. Propiedad intelectual</h2><p>El contenido, diseño y marca de Vitrinexo son propiedad exclusiva de Vitrinexo SpA. Los miembros conservan los derechos sobre el contenido que publican.</p><h2>7. Limitación de responsabilidad</h2><p>Vitrinexo se proporciona "tal como está". No somos responsables de daños derivados del uso de la plataforma.</p><h2>8. Modificaciones</h2><p>Podemos modificar estos términos con previo aviso de 15 días.</p><h2>9. Legislación aplicable</h2><p>Estos términos se rigen por las leyes de Chile. Cualquier disputa se someterá a los tribunales ordinarios de Santiago.</p><h2>10. Contacto</h2><p>Escríbenos a <a href="mailto:hola@vitrinexo.com">hola@vitrinexo.com</a>.</p>';

foreach ([['privacidad','Política de Privacidad',$privacidad_content],['terminos','Términos y Condiciones',$terminos_content]] as [$slug,$title,$content]) {
    $page = get_page_by_path($slug);
    if ($page) { wp_update_post(['ID'=>$page->ID,'post_content'=>$content,'post_status'=>'publish']); echo "Updated: $slug\n"; }
    else { $id=wp_insert_post(['post_title'=>$title,'post_name'=>$slug,'post_content'=>$content,'post_status'=>'publish','post_type'=>'page']); echo "Created: $slug ($id)\n"; }
}
